# Welcome to Jekyll!
# #
# # This config file is meant for settings that affect your whole blog, values
# # which you are expected to set up once and rarely need to edit after that.
# # For technical reasons, this file is *NOT* reloaded automatically when you use
# # 'jekyll serve'. If you change this file, please restart the server process.
#
# # Site settings
title: Nangka
email: your@mail.com
description: > # this means to ignore newlines until "baseurl:"
Welcome to my awesome blog.
baseurl: "/nangka" # the subpath of your site, e.g. /blog
permalink : '/:year/:title'
url: "" # the base hostname & protocol for your site
twitter:
    username: #twitter username here
facebook:
    app_id: 1234
    publisher: 1234
google_plus: #gplus id or username

# Optional settings
github: #your github username
linkedin: #linkedin username
disqus_username: #Your disqus_username to add comments on the post
google_analytics: #your GA unique id (UA-xxxxxxxx-x)

#         # Build settings
markdown: kramdown
gems:
    - jekyll-paginate
    - jekyll-seo-tag
    - jekyll-mentions
    - jemoji
paginate: 5
paginate_path: 'p/:num'
