# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Its Algorithmic The Blog
email: lucasch@cs.umass.edu
description: > # this means to ignore newlines until "baseurl:"
  This is the blog for my site itsalgorithmic.com. I post random thoughts and ideas here. Stay Tuned!
baseurl: "/" # the subpath of your site, e.g. /blog
permalink : '/:year/:title'
url: "mrlucasch.github.io" # the base hostname & protocol for your site
twitter:
  username: "lucasch" #twitter username here
facebook:
    app_id: 1234
    publisher: 1234
google_plus: 

# Optional settings
github: "mrlucasch" #your github username
linkedin: "lucaschaufournier" #linkedin username

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-mentions
  - jemoji
paginate: 5
paginate_path: 'p/:num'
